siteimov/romax/urls.py
from django.urls import include, path
from . import views
from .views import LoginView, ComentarioView

# (. significa que importa views da mesma directoria)


app_name = 'romax' #acho que isto nao é necessario pq so vamos ter uma app!!
urlpatterns = [
    path('', views.landing_page, name='landing_page'),

    path('pesquisa_avancada/', views.pesquisa_avancada, name='pesquisa_avancada'),

    path('resultados_pesquisa/', views.resultados_pesquisa, name='resultados_pesquisa'),

    path('propriedade/<int:propriedade_id>/', views.propriedade, name='propriedade'),

    path('login/', views.login_view, name='login_view'),

    path('logout/', views.logout_view, name='logout_view'),

    path('criar_conta_page/', views.criar_conta_page, name='criar_conta_page'),

    path('criar_conta/', views.criar_conta, name='criar_conta'),

    path('informacao_pessoal/', views.informacaopessoal, name='informacaopessoal'),

    path('informacao_pessoal/salvar_alteracoes_conta/', views.salvar_alteracoes_conta, name='salvar_alteracoes_conta'),

    path('backend/ver_pedidos/', views.ver_pedidos, name='ver_pedidos'),

    path('backend/criar_propriedade_pagina/<int:pedido_id>', views.criar_propriedade_pagina, name='criar_propriedade_pagina' ),

    path('sobre_page', views.sobre_page, name='sobre_page'),

    path('favorito/<int:propriedade_id>', views.favorito, name='favorito'),

    path('favoritos_page', views.favoritos_page, name='favoritos_page'),

    path('propriedades_all', views.propriedades_all, name='propriedades_all'),

    path('imoveis_luxo', views.imoveis_luxo, name='imoveis_luxo'),

    path('publicar_propriedade/', views.publicar_propriedade, name='publicar_propriedade'),

    path('pesquisa_avancada/search_avancada_treat', views.search_avancada_treat, name='search_avancada_treat'),

    path('comentarios', views.comentarios, name='comentarios'),


#REACTS
    path('login_react/', LoginView.as_view(), name='login_react'),

    path('comentario/', ComentarioView.as_view(), name='comentario'),

    path('indexReact', views.indexReact, name='indexReact'),


]

siteimov/siteimov/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('romax.urls')), #aqui normalmente estaria romax no path. para a landing ser localhost/romax
    #perguntar ao mendy se é suposto ir logo p /romax ou pode ficar no localhost... talvez duvida p prof
    #TODO meter isto nas duv file
    path('admin/', admin.site.urls),




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

siteimov/romax/views.py
import os
import re
import string
import datetime
from django.contrib.auth import authenticate
from django.contrib.auth import login, logout
from django.contrib.auth.models import User, Permission
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from rest_framework.views import APIView
from django.urls import reverse_lazy
from django.conf import settings

#from utils import handle_uploaded_file
from .models import CIDADES, CLASSES_ENERGETICAS, SYMBOLS_PASS, SUBTIPO_PROPRIEDADES,TIPOS_PROPRIEDADES
from .models import Propriedade, Cliente, PASSWORD_LEN, ESTADOS_CIVIS, MAX_NAME_LEN, NOME_COMPLETO_REGEX_FORMAT, \
    TELEMOVEL_REGEX_FORMAT,MAX_TITULO_LEN, Comentario ,MAX_MORADA_LEN, NIF_OR_CC_REGEX_FORMAT, AgenteImobiliario, PedidosCriacaoAnuncio, CODIGO_POSTAL_REGEX_FORMAT
from django.db.models import Q
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from django.contrib.auth import authenticate
from django.http import JsonResponse
from rest_framework.views import APIView
from rest_framework.authtoken.models import Token
from django.contrib.auth.models import User

from .serializers import LoginSerializer
from django.contrib.auth.decorators import permission_required
from django.contrib.contenttypes.models import ContentType
EMAIL_VALIDATION_REGEX='^[a-z._-]+@[a-z]+.[a-z]+$' #TODO Voltar aqui

OLDEST_HOUSE_IN_PORTUGAL = 1083
EMAIL_VALIDATION_REGEX_COMPILE = re.compile(EMAIL_VALIDATION_REGEX)
NOME_COMPLETO_REGEX_FORMAT_COMPILE = re.compile(NOME_COMPLETO_REGEX_FORMAT)
TELEMOVEL_REGEX_FORMAT_COMPILE = re.compile(TELEMOVEL_REGEX_FORMAT)
NIF_OR_CC_REGEX_FORMAT_COMPILE = re.compile(NIF_OR_CC_REGEX_FORMAT)

CODIGO_POSTAL_REGEX_FORMAT_COMPILE= re.compile(CODIGO_POSTAL_REGEX_FORMAT)
# Create your views here.

def landing_page(request):
    context = {
        'highlighted_properties': Propriedade.objects.filter(highlighted=True), #TODO ver depois criterio para highlighted ! (ex: mais favoritos, mendy quer por agora todas as highlighted)
        'CIDADES': CIDADES,

        }
    if(request.user.is_authenticated):
        if hasattr(request.user, 'agenteimobiliario'):
            agente = AgenteImobiliario.objects.get(user=request.user)
            nomes = agente.nomeCompleto.split(' ')
        elif hasattr(request.user, 'cliente'):
            cliente = Cliente.objects.get(user=request.user)
            nomes = cliente.nomeCompleto.split(' ')
        context['Cliente_1_nome'] = nomes[0]
        context['Cliente_ultimo_nome'] = nomes[-1]

    return render(request, 'romax/landing_page.html', context=context)

def login_view(request):
    if request.method == 'POST':
        if request.POST['user-email'] and request.POST['password'] and 'user-email' in request.POST and 'password' in request.POST: #se username e pass estao preenchidos
            user = authenticate(username=request.POST['user-email'], password=request.POST['password'])
            if user is not None:
                login(request, user)
                return HttpResponse(status=200, content=reverse('romax:landing_page'))
            else:
               return HttpResponse('Utilizador nao existe', status=401)
        else:
            return HttpResponse(status=400, content='400 Bad Request. HTTP request deve vir com o email e password para poder fazer login')
    else:
        return HttpResponse(status=400, content='400 Bad Request. HTTP request deve ser POST')

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(
        reverse('romax:landing_page')
    )


def propriedade(request, propriedade_id):
    try:
        propriedade = Propriedade.objects.get(pk=propriedade_id)
        favorito = False
        if request.user.is_authenticated:
            if hasattr(request.user, 'agenteimobiliario'):
                favorito = False
            elif hasattr(request.user, 'cliente'):
                cliente = get_object_or_404(Cliente, user=request.user)
                favorito = cliente.salvos.filter(pk=propriedade.id).exists()

        return render(request,
        'romax/propriedade.html',
                      context={'propriedade': propriedade,
                               'favorito': favorito,
                               'nomes_das_img' :  list(filter(lambda i: i.startswith(str(propriedade.id)),os.listdir(settings.MEDIA_ROOT+ '\\imgs_props')))
                               }
                      )
    except (KeyError, Propriedade.DoesNotExist):
        return render(request, 'romax/propriedade_notfound.html', context={
        })

def pesquisa_avancada(request):
    ordernar = [ "Preço ascendente", "Preço descendente", "Maior área", "Menor área", "Mais recente", "Mais antigo"]

    return render(request, 'romax/pesquisa_avancada.html', context={
       'ordernar' : zip(range(1,len(ordernar) ),ordernar),
        'CIDADES':CIDADES,
        'TIPOS_PROPRIEDADES':TIPOS_PROPRIEDADES,
        'SUBTIPO_PROPRIEDADES': SUBTIPO_PROPRIEDADES,
        'CLASSES_ENERGETICAS': CLASSES_ENERGETICAS
    })

def resultados_pesquisa(request):
    #TODO possivel incremento pesquisa pelo titulo sera based num regex (case insensitive) *titulo*

    parametros_pesquisa = request.POST

    parametros_pesquisa['Cidade']
    parametros_pesquisa['titulo']

    pesquisa_cliente = Q()

    id_cidade=int(parametros_pesquisa['Cidade'])
    match id_cidade:
        case -1:
            pass
        case id_cidade if id_cidade in range(len(CIDADES)):
            pesquisa_cliente.add(Q(cidade=id_cidade),Q.AND)
        case _:
            pass #TODO lancçar erro ou algo

    titulo = parametros_pesquisa.get('titulo', '')

    if titulo != '':
        pesquisa_cliente &= Q(titulo__icontains=titulo)
        #pesquisa_cliente.add(Q(titulo=parametros_pesquisa['titulo']), Q.AND)

    return render(request, 'romax/resultados_pesquisas.html', context ={
        'Resultados': Propriedade.objects.filter(pesquisa_cliente)
    })

def criar_conta_page(request):
    return render(request, 'romax/criar_conta_page.html', context = {
        'ESTADOS_CIVIS' : ESTADOS_CIVIS,
        'MAX_NAME_LEN' : MAX_NAME_LEN,
        'NOME_COMPLETO_REGEX_FORMAT': NOME_COMPLETO_REGEX_FORMAT,
        'TELEMOVEL_REGEX_FORMAT' : TELEMOVEL_REGEX_FORMAT,
        'NIF_OR_CC_REGEX_FORMAT' : NIF_OR_CC_REGEX_FORMAT,
        'PASSWORD_LEN' : PASSWORD_LEN,
        'SYMBOLS_PASS' : SYMBOLS_PASS,
        'PASSWORD_LEN' : PASSWORD_LEN
    })
def publicar_propriedade(request):
    PedidosCriacaoAnuncio.objects.create(user_id=request.user)

    return HttpResponseRedirect(
        reverse('romax:landing_page')
    )
def criar_conta(request):
    # TODO page para se nao foi possivel criar conta (failed server-side validation or server error (5xx))

    #Validar o email
    email_valido = bool(re.fullmatch(EMAIL_VALIDATION_REGEX_COMPILE,request.POST['email']))

    #validar o nome completo
    nome_completo = request.POST['nome-completo']
    is_valid_length = 0 < len(nome_completo) <= MAX_NAME_LEN
    is_valid_format = bool(re.fullmatch(NOME_COMPLETO_REGEX_FORMAT_COMPILE, nome_completo))


    #validar Telemovel
    telemovel = request.POST['telemovel']
    tel_valido = bool(re.fullmatch(TELEMOVEL_REGEX_FORMAT_COMPILE, telemovel))
    telemovel = transformar_em_tel(telemovel)

    #Validar idade se Cliente inseriu uma
    if('idade' in request.POST):
        idade_valida = 18 <= int(request.POST['idade']) <=122

    #TODO validar Estado Civil se Cliente inseriu um
    estado_civil_valido = int(request.POST['Estado-Civil']) in list(ESTADOS_CIVIS.keys())

    #validar password
    pass_valida = pass_tem_requisitos(request.POST['password'])

    if( not (email_valido and pass_valida and estado_civil_valido and  idade_valida and tel_valido and is_valid_format and is_valid_length) ):
        return HttpResponse(status=401, content="Há um campo invalido")
    #url:
    myfile = request.FILES.get('myfile')
    if myfile:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        # verificar se foto ja existe no media dir
        if fs.exists(myfile.name):
            fs.delete(myfile.name)

        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
    else:
        uploaded_file_url=''
    #Criar conta
    try:
        if not User.objects.filter(username=request.POST['email']).exists():
            user = User.objects.create_user(request.POST['email'],
                                        request.POST['email'],
                                        request.POST['password'])
        else:
            return render(request, 'romax/criar_conta_page.html', context={'error_msg': "User ja existe",})
    except:
        pass #Enviar ao user uma resposta de erro (5XX)
    try:
        Cliente.objects.create(
            user=user,
            nomeCompleto =nome_completo,
            telemovel = telemovel,
            idade = None if 'idade' not in request.POST else int(request.POST['idade']),
            estadoCivil = int(request.POST['Estado-Civil']),
            nif = int(request.POST['NIF'].replace(' ', '')),
            cc = request.POST['CC'].replace(' ', ''),
            animais = 'tem-animais' in request.POST,
            urlprofilepic = uploaded_file_url
        )
    except Exception as e:
        print(e)
        user.delete()
    return HttpResponseRedirect(reverse('romax:landing_page'))

def informacaopessoal(request):
    return render(request, 'romax/informacao_pessoal.html')

def salvar_alteracoes_conta(request):
    if request.method == 'POST':
        # Validar o email
        email_valido = bool(re.fullmatch(EMAIL_VALIDATION_REGEX_COMPILE, request.POST['email']))

        # validar o nome completo
        nome_completo = request.POST['nome-completo']
        is_valid_length = 0 < len(nome_completo) <= MAX_NAME_LEN

siteimov/romax/templates/romax/base_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}

    <title>ROMAX</title>

    <link rel="icon" type="image/x-icon" href="{% static 'romax/images/favicon.png' %}">

   {# jQuery links #}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    {#  Bootstrap links #}
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'romax/CSS/base_page.css' %}">
    {% block css_of_rest_of_page %}
    {% endblock %}
</head>
<body>
    <nav id="Header" >
        {# INFO: This nav is the header #}
        <a  href="{% url 'romax:landing_page' %}" style="padding: 0;  height: 100%; display: initial; box-sizing: border-box">
           <img id="logo" src="{% static 'romax/images/newnew.jpg' %}" alt="Logo" >
        </a>

        <div class="nav-links-user">
            {% if request.user.is_authenticated and request.user.agenteimobiliario %}
            <a href="{% url 'romax:ver_pedidos' %}">Ver Pedidos</a>
            {% endif %}
            <a href="{% url 'romax:imoveis_luxo' %}">Imóveis de Luxo</a>
            <a href="{% url 'romax:propriedades_all' %}">Propriedades</a>


            {% if  request.user.is_authenticated %}
                {% if request.user.cliente %}

                    <a href="{% url 'romax:publicar_propriedade' %}">Vender</a>
                    <a style="margin-left: auto;" href="{% url 'romax:favoritos_page' %}">Favoritos</a>
                {% endif %}
                <a style="margin-left: auto;" href="{% url 'romax:logout_view' %}">Logout</a>
                <a href="{% url 'romax:informacaopessoal' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16"><path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/><path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/></svg>
                </a>
            {% else %}
                <a style=" margin-left: auto;" onclick="login_registar_dialog.showModal()">
                <svg style="margin-right: 6px;margin-bottom: 3px" xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-person-lines-fill" viewBox="0 0 16 16"><path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zM11 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5m.5 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1zm0 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1z"/></svg>
                Entrar
                </a>
            {% endif %}

        </div>
    </nav>
    <main>
        {% block rest_of_page %}
        {%  endblock %}
    </main>


    <!-- FOOTER: -->

    <footer class="footer-section">
        <hr style="border-color: #4a4848">
        <div class="container">
            <div class="footer-cta pt-5 pb-5">
                <div class="row">
                    <div class="col-xl-4 col-md-4 mb-30">
                        <div class="single-cta">
                            <div class="cta-text">
                                <h4>Onde nos encontrar</h4>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16"><path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10m0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6"/></svg>
                                <span>Av. de Berna 160, 1050-099, Lisboa</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-4 mb-30">
                        <div class="single-cta">
                            <div class="cta-text">
                                <h4>Ligue-nos</h4>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z"/></svg>
                                <span>296 909 391</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-4 mb-30">
                        <div class="single-cta">
                            <div class="cta-text">
                                <h4>Contacte-nos via email</h4>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16"><path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414zM0 4.697v7.104l5.803-3.558zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586zm3.436-.586L16 11.801V4.697z"/></svg>
                                <span>romax@info.pt</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="footer-content pt-5 pb-5">
                <div class="row">
                    <div class="col-xl-4 col-lg-4 mb-50">
                        <div class="footer-widget">
                            <div class="footer-logo">
                                <a href=""><img src="{% static 'romax/images/newnew.jpg' %}" class="img-fluid" alt="logo"></a>
                            </div>
                            <div class="footer-text">
                                <p>Encontre o lar dos seus sonhos conosco na ROMAX. A nossa equipa está pronta para
                                    tornar a sua jornada imobiliária uma experiência memorável.
                                </p>
                            </div>
                            <div class="footer-social-icon">
                                <span>Siga-nos</span>
                                <a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16"><path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/></svg></a>
                                <a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16"><path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/></svg></a>
                                <a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16"><path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/></svg></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-4 col-md-6 mb-30">
                        <div class="footer-widget">
                            <div class="footer-widget-heading">
                                <h3>Links Úteis</h3>
                            </div>
                            <ul>
                                <li><a href="{% url 'romax:landing_page' %}">Página Inicial</a></li>
                                <li><a href="{% url 'romax:sobre_page' %}">Sobre Nós</a></li>
                                <li><a href="#">Serviços</a></li>
                                <li><a href="#">Contactos Administrativos</a></li>
                                <li><a href="{% url 'romax:comentarios' %}">Comentários</a></li>
                                <li><a href="#">A nossa equipa</a></li>
                                <li><a href="#">Sede</a></li>
                                <li><a href="#">Notícias Mais Recentes</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-4 col-md-6 mb-50">
                        <div class="footer-widget">
                            <div class="footer-widget-heading">
                                <h3>Subscreva</h3>
                            </div>
                            <div class="footer-text mb-25">
                                <p>Não perca mais nenhum anúncio, subscreva à nossa newsletter</p>
                            </div>
                            <div class="subscribe-form">
                                <form action="#">
                                    <input type="text" placeholder="Email">
                                    <button><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-send" viewBox="0 0 16 16"><path d="M15.854.146a.5.5 0 0 1 .11.54l-5.819 14.547a.75.75 0 0 1-1.329.124l-3.178-4.995L.643 7.184a.75.75 0 0 1 .124-1.33L15.314.037a.5.5 0 0 1 .54.11ZM6.636 10.07l2.761 4.338L14.13 2.576zm6.787-8.201L1.591 6.602l4.339 2.76z"/></svg>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </footer>

















{% if not request.user.is_authenticated %}
    <dialog id="login_registar_dialog">
        <div  class="close_cross_wrapper" onclick="login_registar_dialog.close()">
            {% include "romax/cruz.html" %}
        </div>
        <main >
            <h3>Entrar</h3>
            <form id='login-form' action="{% url 'romax:login_view' %}" method="post" >
                {% csrf_token %}
                <div class="mb-3">
                  <label for="user-email" class="form-label">Endereço de Email</label>
                  <input type="email" class="form-control" id="user-email" name="user-email"  required >
                </div>
                <div class="mb-3">
                  <label for="password" class="form-label">Password</label>
                  <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <p id="msg-email-pass-invalidas" style="color: red" hidden="">E-mail ou password invalidas</p>
                <div id="entrar_botao">
                        <button type="submit" class="btn btn-primary">Entrar</button>
                </div>
            </form>
            <script src="/static/romax/javascript/login.js">
            </script>
            <hr>
            <h3>Não tens conta?</h3>
            <a href="{% url 'romax:criar_conta_page' %}" class="btn btn-outline-secondary">Clica aqui para criar</a>
        </main>
    </dialog>
{% endif %}

</body>
</html>

siteimov/romax/templates/romax/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + React</title>
    <script type="module" crossorigin src="/static/romax/javascript/index-CMFe-eEh.js"></script>
    <link rel="stylesheet" crossorigin href="static/romax/CSS/index-C_k8558H.css">
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>

siteimov/romax/templates/romax/ver_pedidos.html
{% extends 'romax/base_page_BACKEND.html' %}

{% block BACKEND_css_rest_of_page %}
    #title {
        font-size: xxx-large;
        text-align: center;
        padding-bottom: 30px;
    }
{%  endblock %}

{% block BACKEND_rest_of_page %}
<h1 id="title">Pedidos</h1>
<div class="list-group">

    {% for pedido in Pedidos %}
        <a href="{% url 'romax:criar_propriedade_pagina' pedido.id %}" class="list-group-item list-group-item-action " aria-current="true">
            <h2>Pedido de: {{ pedido.user_id }}</h2>
            <small>em {{ pedido.data_pedido }}</small>
        </a>
    {% empty %}
        <a class="list-group-item disabled" href="#">Não há pedidos por tratar</a>
    {% endfor %}
</div>
{%  endblock %}